---
title: "Scup data exploration"
author: "Catalina Roman"
date: "2023-11-29"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(tidyverse)
library(here)
library(sf)
library(patchwork)
library(boot)
library(infer)
library(broom)
library(gridExtra)
library(viridis)
source(here("R", "StratMeanFXs_v2.R")) #removed SEASON group for the purposes of the resampling
```

```{r data, include= FALSE, message = FALSE}
# full data set 
# complete_data <- readRDS(here("data", "rds", "merged_data_complete.rds")) |> filter(SVSPP == 121) |> mutate(EXPCATCHWT = ifelse(is.na(EXPCATCHWT), 0, EXPCATCHWT))
scup_complete <- readRDS(here("data", "rds", "completed_bts_data.rds")) |> filter(SVSPP == 143) |> mutate(EXPCATCHWT = ifelse(is.na(EXPCATCHWT), 0, EXPCATCHWT))

# total biomass of scup in the spring for a given stratum 
scup_bio_fall <- readRDS(here("data", "rds", "total-biomass_impacted-species.rds")) |> 
  filter(SEASON == "FALL", SVSPP == 143)
scup_bio_spring <- readRDS(here("data", "rds", "total-biomass_impacted-species.rds")) |> 
  filter(SEASON == "SPRING", SVSPP == 143)

# filtered_data <- readRDS(here("data", "rds", "95filtered_complete_bts.rds")) |> filter(SVSPP == 121) |> mutate(EXPCATCHWT = ifelse(is.na(EXPCATCHWT), 0, EXPCATCHWT))

# read the strata shapefile in to plot the polygons based on proportion and overlay the tow points
strata <- readRDS(here("data", "rds", "active_strata.rds")) 

# wind areas 
wind_areas <- readRDS(here("data", "rds", "all_wind_areas_Jun2022.rds")) 
wind_areas2 <- readRDS(here("data", "rds", "all_wind_areas_Jan2023.rds")) 

coastline <- sf::st_read(dsn = here("gis", "eastern_coast_UTM.shp"))


full_years <- c(2009:2016, 2018, 2019, 2021)

```

## Summary 
```{r more data, message = FALSE, include = FALSE}
# full data set 
# raw_data <- read_csv(here("data", "raw-data", "NEFSC_BTS_ALLCATCHES.csv")) |> 
#   filter(SVSPP == 121, EST_YEAR %in% c(2009:2021)) |> 
#   mutate(SVSPP = as.integer(SVSPP), 
#          STATION = as.integer(STATION), 
#          STRATUM = as.integer(STRATUM))
# 
# add_info <- raw_data |> 
#   select(SVSPP, CRUISE6, STATION, STRATUM, BOTTEMP, AREA_SWEPT_WINGS_MEAN_KM2, SEASON)
# 
# filtered_data <- filtered_data |> 
#   left_join(add_info, by = c("SVSPP", "STRATUM", "CRUISE6", "STATION", "SEASON"))
  
```




```{r}
scup_summary_spring <- scup_complete |> 
  filter(!is.na(AVGDEPTH), SEASON == "SPRING", YEAR %in% full_years) |> 
  group_by(EST_YEAR) |>
  summarise(med_wt = median(EXPCATCHWT), 
            max_wt = max(EXPCATCHWT), 
            range_wt = max_wt - med_wt, 
            avg_wt = mean(EXPCATCHWT), 
            sd_wt = sd(EXPCATCHWT), 
            lower = quantile(EXPCATCHWT, 0.05), 
            upper = quantile(EXPCATCHWT, 0.95), 
            tow_ct = length(unique(TOWID)))
scup_summary_spring

scup_summary_fall <- scup_complete |> 
  filter(!is.na(AVGDEPTH), SEASON == "FALL", YEAR %in% full_years) |> 
  group_by(EST_YEAR) |>
  summarise(med_wt = median(EXPCATCHWT), 
            max_wt = max(EXPCATCHWT), 
            range_wt = max_wt - med_wt, 
            avg_wt = mean(EXPCATCHWT), 
            sd_wt = sd(EXPCATCHWT), 
            lower = quantile(EXPCATCHWT, 0.05), 
            upper = quantile(EXPCATCHWT, 0.95), 
            tow_ct = length(unique(TOWID)))
scup_summary_fall

scup_complete_spring <- scup_complete |>
  filter(SEASON == "SPRING", YEAR %in% full_years) |>
  summarise(quantile(EXPCATCHWT, 0.95), 
            quantile(EXPCATCHWT, 0.975), 
            quantile(EXPCATCHWT, 0.99)) 

scup_complete_fall <- scup_complete |> 
  filter(SEASON == "FALL", YEAR %in% full_years) |>
  summarise(quantile(EXPCATCHWT, 0.95), 
            quantile(EXPCATCHWT, 0.975), 
            quantile(EXPCATCHWT, 0.99)) 

```

```{r}
scup_csum_spring <- scup_bio_spring |> 
  mutate(csum_bio = cumsum(EXPCATCHWT), 
         csum_prop = csum_bio/max(csum_bio))
  
scup_csum_spring
  
p1<- ggplot(scup_csum_spring) + 
  geom_point(aes(x = fct_reorder(as.character(STRATUM), csum_bio), y = csum_bio)) + 
  ylim(0, NA) + 
  geom_hline(yintercept = 0.95*max(scup_csum_spring$csum_bio),color = "red") +
  geom_hline(yintercept = 0.99*max(scup_csum_spring$csum_bio),color = "blue") +
  labs(x = "Stratum", y = "Cumulative Biomass (kg)", 
       title = "Scup Cumulative Distribution of Biomass \nSpring") +
  theme_bw() + theme(plot.title = element_text(size=10)) +
  theme(axis.text.x = element_text(angle = 90, size = 5))

#------------------------------------------------------------  
scup_csum_fall <- scup_bio_fall |> 
  mutate(csum_bio = cumsum(EXPCATCHWT), 
         csum_prop = csum_bio/max(csum_bio))
  
scup_csum_fall
  
p2<- ggplot(scup_csum_fall) + 
  geom_point(aes(x = fct_reorder(as.character(STRATUM), csum_bio), y = csum_bio)) + 
  ylim(0, NA) + 
  geom_hline(yintercept = 0.95*max(scup_csum_fall$csum_bio),color = "red") +
  geom_hline(yintercept = 0.99*max(scup_csum_fall$csum_bio),color = "blue") +
  labs(x = "Stratum", y = "Cumulative Biomass (kg)", 
       title = "Scup Cumulative Distribution of Biomass \nFall") +
  theme_bw() + theme(plot.title = element_text(size=10)) +
  theme(axis.text.x = element_text(angle = 90, size = 5))

grid.arrange(p1,p2,ncol=2)
```

```{r}
scup_strata_spring <- right_join(scup_csum_spring, strata, by = "STRATUM") |> # join the filtered data to the strata shapefile; coearces the shapefile into a dataframe 
  na.omit() |> # remove NAs
  st_sf()


scup_strata_fall <- right_join(scup_csum_fall, strata, by = "STRATUM") |> # join the filtered data to the strata shapefile; coearces the shapefile into a dataframe 
  na.omit() |> # remove NAs
  st_sf()


scup_95_spring <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_strata_spring |> filter(csum_prop <= 0.95), fill = "#5dc5e9")+ #fill the strata polygons based on the values in the csum_prop column
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    labs(title = "Scup 95% \nCumulative Distribution \nSpring", 
         x = "Longitude", y = "Latitude", fill = "95% Distribution") +
    theme_bw() + theme(plot.title = element_text(size=10)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()) 

scup_99_spring <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_strata_spring |> filter(csum_prop <= 0.99), fill = "#5dc5e9")+ 
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    labs(title = "Scup 99% \nCumulative Distribution \nSpring", 
         x = "Longitude", y = "Latitude", fill = "99% Distribution") +
    theme_bw() + theme(plot.title = element_text(size=10)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()) 

scup_all_spring <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_strata_spring, fill = "#5dc5e9")+ 
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    labs(title = "Scup \nCumulative Distribution \nSpring", 
         x = "Longitude", y = "Latitude", fill = "Distribution") +
    theme_bw() + theme(plot.title = element_text(size=10)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()) 
#-----------------------------------------------------------

scup_95_fall <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_strata_fall |> filter(csum_prop <= 0.95), fill = "#5dc5e9")+ 
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    labs(title = "Scup 95% \nCumulative Distribution \nFall", 
         x = "Longitude", y = "Latitude", fill = "95% Distribution") +
    theme_bw() + theme(plot.title = element_text(size=10)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()) 

scup_99_fall <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_strata_fall |> filter(csum_prop <= 0.99), fill = "#5dc5e9")+ 
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    labs(title = "Scup 99% \nCumulative Distribution \nFall", 
         x = "Longitude", y = "Latitude", fill = "99% Distribution") +
    theme_bw() + theme(plot.title = element_text(size=10)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()) 

scup_all_fall <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_strata_fall, fill = "#5dc5e9")+ 
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    labs(title = "Scup \nCumulative Distribution \nFall", 
         x = "Longitude", y = "Latitude", fill = "Distribution") +
    theme_bw() + theme(plot.title = element_text(size=10)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()) 


grid.arrange(scup_95_spring,scup_99_spring,scup_all_spring, ncol=3)
grid.arrange(scup_95_fall,scup_99_fall,scup_all_fall,ncol=3)

grid.arrange(scup_99_spring, scup_99_fall, ncol=2)


```
Cumulative Distribution remove outliers 
```{r}
scup_csum_spring_no.out <- scup_complete |> 
  filter(YEAR %in% full_years, SEASON == "SPRING", EXPCATCHWT <= quantile(EXPCATCHWT, 0.99)) |> 
  group_by(STRATUM, SEASON) |> 
  summarise(total_bio = sum(EXPCATCHWT), .groups = "drop") |> 
  arrange(desc(total_bio)) |>
  mutate(csum_bio = cumsum(total_bio), 
         csum_prop = csum_bio/max(csum_bio))


p1.no.out <- ggplot(scup_csum_spring_no.out) + 
  geom_point(aes(x = fct_reorder(as.character(STRATUM), csum_bio), y = csum_bio)) + 
  ylim(0, NA) + 
  geom_hline(yintercept = 0.95*max(scup_csum_spring_no.out$csum_bio),color = "red") +
  geom_hline(yintercept = 0.99*max(scup_csum_spring_no.out$csum_bio),color = "blue") +
  labs(x = "Stratum", y = "Cumulative Biomass (kg)", 
       title = "Scup Cumulative Distribution of Biomass \nSpring", 
       subtitle = "Biomass observations greater than the 99th quantile \nwere removed from the distribution") +
  theme_bw() + theme(plot.title = element_text(size=10),plot.subtitle = element_text(size=7)) +
  theme(axis.text.x = element_text(angle = 90, size = 5))

scup_csum_fall_no.out <- scup_complete |> 
  filter(YEAR %in% full_years, SEASON == "FALL", EXPCATCHWT <= quantile(EXPCATCHWT, 0.99)) |> 
  group_by(STRATUM, SEASON) |> 
  summarise(total_bio = sum(EXPCATCHWT), .groups = "drop") |> 
  arrange(desc(total_bio)) |>
  mutate(csum_bio = cumsum(total_bio), 
         csum_prop = csum_bio/max(csum_bio))

p2.no.out <- ggplot(scup_csum_fall_no.out) + 
  geom_point(aes(x = fct_reorder(as.character(STRATUM), csum_bio), y = csum_bio)) + 
  ylim(0, NA) + 
  geom_hline(yintercept = 0.95*max(scup_csum_fall_no.out$csum_bio),color = "red") +
  geom_hline(yintercept = 0.99*max(scup_csum_fall_no.out$csum_bio),color = "blue") +
  labs(x = "Stratum", y = "Cumulative Biomass (kg)", 
       title = "Scup Cumulative Distribution of Biomass \nFall", 
       subtitle = "Biomass observations greater than the 99th quantile \nwere removed from the distribution") +
  theme_bw() + theme(plot.title = element_text(size=10),plot.subtitle = element_text(size=7)) +
  theme(axis.text.x = element_text(angle = 90, size = 5))

grid.arrange(p1.no.out,p2.no.out,ncol=2)
```

```{r}
scup_no.out_spring <- right_join(scup_csum_spring_no.out, strata, by = "STRATUM") |> # join the filtered data to the strata shapefile; coearces the shapefile into a dataframe 
  na.omit() |> # remove NAs
  st_sf()


scup_95_spring_no.out <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_no.out_spring |> filter(csum_prop <= 0.95), fill = "#5dc5e9")+ 
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    #geom_point(data = x, mapping = aes(DECDEG_BEGLON, DECDEG_BEGLAT, alpha = 0.4), color = "white")
    facet_wrap(~SEASON) + 
    labs(title = "Scup 95% \nCumulative Distribution \nSpring", 
         x = "Longitude", y = "Latitude", fill = "95% Distribution", 
         subtitle = "Biomass observations greater than the 99th quantile \nwere removed from the distribution") +
    theme_bw() + theme(plot.title = element_text(size=10),plot.subtitle = element_text(size=7)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()) 

scup_99_spring_no.out <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_no.out_spring |> filter(csum_prop <= 0.99), fill = "#5dc5e9")+ 
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    #geom_point(data = x, mapping = aes(DECDEG_BEGLON, DECDEG_BEGLAT, alpha = 0.4), color = "white")
    facet_wrap(~SEASON) + 
    labs(title = "Scup 99% \nCumulative Distribution \nSpring", 
         x = "Longitude", y = "Latitude", fill = "99% Distribution", 
         subtitle = "Biomass observations greater than the 99th quantile \nwere removed from the distribution") +
    theme_bw() + theme(plot.title = element_text(size=10),plot.subtitle = element_text(size=7)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()) 

scup_all_spring_no.out <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_no.out_spring, fill = "#5dc5e9")+ 
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    #geom_point(data = x, mapping = aes(DECDEG_BEGLON, DECDEG_BEGLAT, alpha = 0.4), color = "white")
    facet_wrap(~SEASON) + 
    labs(title = "Scup \nCumulative Distribution \nSpring", 
         x = "Longitude", y = "Latitude", fill = "Distribution", 
         subtitle = "Biomass observations greater than the 99th quantile \nwere removed from the distribution") +
    theme_bw() + theme(plot.title = element_text(size=10),plot.subtitle = element_text(size=7)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()) 


#------------------------------------------------------------------------------------
scup_no.out_fall <- right_join(scup_csum_fall_no.out, strata, by = "STRATUM") |> # join the filtered data to the strata shapefile; coearces the shapefile into a dataframe 
  na.omit() |> # remove NAs
  st_sf()


scup_95_fall_no.out <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_no.out_fall |> filter(csum_prop <= 0.95), fill = "#5dc5e9")+ 
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    #geom_point(data = x, mapping = aes(DECDEG_BEGLON, DECDEG_BEGLAT, alpha = 0.4), color = "white")
    facet_wrap(~SEASON) + 
    labs(title = "Scup 95% \nCumulative Distribution \nFall", 
         x = "Longitude", y = "Latitude", fill = "95% Distribution", 
         subtitle = "Biomass observations greater than the 99th quantile \nwere removed from the distribution") +
    theme_bw() + theme(plot.title = element_text(size=10),plot.subtitle = element_text(size=7)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()) 

scup_99_fall_no.out <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_no.out_fall |> filter(csum_prop <= 0.99), fill = "#5dc5e9")+ 
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    #geom_point(data = x, mapping = aes(DECDEG_BEGLON, DECDEG_BEGLAT, alpha = 0.4), color = "white")
    facet_wrap(~SEASON) + 
    labs(title = "Scup 99% \nCumulative Distribution \nFall", 
         x = "Longitude", y = "Latitude", fill = "99% Distribution", 
         subtitle = "Biomass observations greater than the 99th quantile \nwere removed from the distribution") +
    theme_bw() + theme(plot.title = element_text(size=10),plot.subtitle = element_text(size=7)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()) 

scup_all_fall_no.out <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_no.out_fall, fill = "#5dc5e9")+ 
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    #geom_point(data = x, mapping = aes(DECDEG_BEGLON, DECDEG_BEGLAT, alpha = 0.4), color = "white")
    facet_wrap(~SEASON) + 
    labs(title = "Scup \nCumulative Distribution \nFall", 
         x = "Longitude", y = "Latitude", fill = "Distribution", 
         subtitle = "Biomass observations greater than the 99th quantile \nwere removed from the distribution") +
    theme_bw() + theme(plot.title = element_text(size=10),plot.subtitle = element_text(size=7)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()) 


grid.arrange(scup_95_spring_no.out,scup_99_spring_no.out,scup_all_spring_no.out, ncol=3)

grid.arrange(scup_95_fall_no.out,scup_99_fall_no.out,scup_all_fall_no.out, ncol=3)

```



```{r}
library(gghighlight)
library(ggsflabel)

ggplot(strata) + 
  geom_sf(aes(fill = as.factor(Depth_m), geometry=Shape)) +  
  scale_fill_manual(values = c("#d48a3a", "#afdb88", "#21c99b", "#e2b29b", "#ff6fcf","#e8f5cc","#6274db","#80e6e6","#b0b1fa")) 
 # geom_sf_label(aes(label=STRATUM), fun.geometry = sf::st_centroid) +
 


(map1<- strata |> subset(Depth_m %in% ">183") |>
    ggplot() + geom_sf(data = coastline, fill = "grey60", color = "black") + 
 geom_sf(fill = "#d48a3a", color="black") + ggtitle(">183") +
 geom_sf_text(aes(label=STRATUM), size=4, color="blue", family="sans"))

(map2<- strata |> subset(Depth_m %in% "110-183") |>
    ggplot() + geom_sf(data = coastline, fill = "grey60", color = "black") + 
 geom_sf(fill = "#afdb88", color="black") + ggtitle("110-183") +
 geom_sf_text(aes(label=STRATUM), size=4, color="blue", family="sans"))

(map3<- strata |> subset(Depth_m %in% "18-27") |>
    ggplot() + geom_sf(data = coastline, fill = "grey60", color = "black") + 
 geom_sf(fill = "#21c99b", color="black") + ggtitle("18-27") +
 geom_sf_text(aes(label=STRATUM), size=2, color="blue", family="sans"))

(map4<- strata |> subset(Depth_m %in% "27-46") |>
    ggplot() +  geom_sf(data = coastline, fill = "grey60", color = "black") + 
 geom_sf(fill = "#e2b29b", color="black") + ggtitle("27-46") +
 geom_sf_text(aes(label=STRATUM), size=4, color="blue", family="sans"))

(map5<- strata |> subset(Depth_m %in% "27-55") |>
    ggplot() + geom_sf(data = coastline, fill = "grey60", color = "black") + 
 geom_sf(fill = "#ff6fcf", color="black") + ggtitle("27-55") +
 geom_sf_text(aes(label=STRATUM), size=4, color="blue", family="sans"))

(map6<- strata |> subset(Depth_m %in% "46-55") |>
    ggplot() + geom_sf(data = coastline, fill = "grey60", color = "black") + 
 geom_sf(fill = "#e8f5cc", color="black") + ggtitle("46-55") +
 geom_sf_text(aes(label=STRATUM), size=4, color="blue", family="sans"))

(map7<- strata |> subset(Depth_m %in% "55-110") |>
    ggplot() + geom_sf(data = coastline, fill = "grey60", color = "black") + 
 geom_sf(fill = "#6274db", color="black") + ggtitle("55-110") +
 geom_sf_text(aes(label=STRATUM), size=4, color="red", family="sans"))

(map8<- strata |> subset(Depth_m %in% "9-27") |>
    ggplot() + geom_sf(data = coastline, fill = "grey60", color = "black") + 
 geom_sf(fill = "#80e6e6", color="black") + ggtitle("9-27") +
 geom_sf_text(aes(label=STRATUM), size=4, color="blue", family="sans"))

(map9<- strata |> subset(Depth_m %in% "9-35") |>
    ggplot() + geom_sf(data = coastline, fill = "grey60", color = "black") + 
 geom_sf(fill = "#b0b1fa", color="black") + ggtitle("9-35") +
 geom_sf_text(aes(label=STRATUM), size=4, color="blue", family="sans"))


map10<- strata |>
 ggplot() + geom_sf(data = coastline, fill = "grey60", color = "black") + 
 geom_sf(fill = "#ffffcc", color="black")  +
 geom_sf(data = wind_areas, fill="#ff9966", color="#330000")

map11<- strata |>
 ggplot() + geom_sf(data = coastline, fill = "grey60", color = "black") + 
 geom_sf(fill = "#ffffcc", color="black")  +
 geom_sf(data = wind_areas2, fill="#ccffff", color="#0099cc")



scup_strata_spring <- right_join(scup_csum_spring, strata, by = "STRATUM") |> # join the filtered data to the strata shapefile; coearces the shapefile into a dataframe 
  na.omit() |> # remove NAs
  st_sf()


scup_strata_fall <- right_join(scup_csum_fall, strata, by = "STRATUM") |> # join the filtered data to the strata shapefile; coearces the shapefile into a dataframe 
  na.omit() |> # remove NAs
  st_sf()



ggplot(strata) + 
  geom_sf(aes(fill = as.factor(Depth_m), geometry=Shape)) +  
  scale_fill_manual(values = c("#d48a3a", "#afdb88", "#21c99b", "#e2b29b", "#ff6fcf","#e8f5cc","#6274db","#80e6e6","#b0b1fa")) +
   geom_sf(data = subset(strata, STRATUM %in% c(1660,1620)), fill = "red") 
 # geom_sf_label(aes(label=STRATUM), fun.geometry = sf::st_centroid) +

```

Add additional strata to the 99 cumulative distribution

strata fall 
(3450, 1050, 1610, 1090, 3410, 3380, 3020, 3460 ,3050, 3440, 3260, 3350, 8510, 1010, 1060, 3080, 3230, 3320, 3290, 8500, 1650, 1690, 7520, 1100, 3110, 3140, 3170)
add to fall
(1020,1740,1700,1730,3200)
add wind areas overlap
(1660,1620)

strata spring
(1020, 1750, 1060, 1030, 3450, 1740, 1760, 1700, 1710, 3020, 1050, 1670, 1690, 1010, 8500)
add to spring
(1730, 1650, 1610, 1660, 1620, 8510, 1630, 8520, 1680, 1640, 8530)
add wind areas overlap
(3110, 1090,1100,3170,3200,3230,3260,3290)


```{r}

strat_99_fall <- scup_strata_fall |> filter(csum_prop <= 0.99) 
strat_99_fall$STRATUM


#strata fall 
strata_include_fall <- c(3450, 1050, 1610, 1090, 3410, 3380, 3020, 3460 ,3050, 3440, 3260, 3350, 8510, 1010,
1060, 3080, 3230, 3320, 3290, 8500, 1650, 1690, 7520, 1100, 3110, 3140, 3170, 1020,1740,1700,1730,3200, 1660,1620
)


scup_stratafilter_fall <- scup_strata_fall |> 
  subset(STRATUM %in% strata_include_fall)

strat_99_spring <- scup_strata_spring |> filter(csum_prop <= 0.99) 
strat_99_spring$STRATUM

#strata spring
strata_include_spring <- c(1020, 1750, 1060, 1030, 3450, 1740, 1760, 1700, 1710, 3020, 1050, 1670, 1690, 1010, 8500, 
1730, 1650, 1610, 1660, 1620, 8510, 1630, 8520, 1680, 1640, 8530,3110, 1090,1100,3170,3200,3230,3260,3290)

scup_stratafilter_spring <- scup_strata_spring |> 
  subset(STRATUM %in% strata_include_spring) 





(scup_strata_in_fall <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_stratafilter_fall, fill = "#5dc5e9") +
    geom_sf(data = wind_areas2, fill="#ede04b", color="grey80") +
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    #geom_point(data = x, mapping = aes(DECDEG_BEGLON, DECDEG_BEGLAT, alpha = 0.4), color = "white")
    labs(title = "Scup strata in \nFall", 
         x = "Longitude", y = "Latitude", fill = "", 
         subtitle = "") +
    theme_bw() + theme(plot.title = element_text(size=10),plot.subtitle = element_text(size=7)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank()))


scup_strata_in_spring <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = scup_stratafilter_spring, fill = "#5dc5e9") +
    geom_sf(data = wind_areas2, fill="#ede04b", color="grey80") +
    scale_fill_distiller(palette = 8) +
    coord_sf() +
    #geom_point(data = x, mapping = aes(DECDEG_BEGLON, DECDEG_BEGLAT, alpha = 0.4), color = "white")
    labs(title = "Scup strata in \nSpring", 
         x = "Longitude", y = "Latitude", fill = "", 
         subtitle = "") +
    theme_bw() + theme(plot.title = element_text(size=10),plot.subtitle = element_text(size=7)) +
    theme(legend.position = "bottom", 
          panel.grid = element_blank())

grid.arrange(scup_strata_in_spring,scup_strata_in_fall,ncol=2)



```
Data
```{r}
unique(scup_complete$STRATUM)
strata_include_fall <- c(3450,1050,1610,1090,3410,3380,3020,3460,3050,3440,3260,3350,8510,1010,1060,3080,3230, 3320,3290,8500,1650,1690,7520,1100,3110,3140,3170,1020,1740,1700,1730,3200,1660,1620)

strata_include_spring <- c(1020, 1750, 1060, 1030, 3450, 1740, 1760, 1700, 1710, 3020, 1050, 1670, 1690, 1010, 8500,1730, 1650, 1610, 1660, 1620, 8510, 1630, 8520, 1680, 1640, 8530,3110, 1090,1100,3170,3200,3230,3260,3290)

### filter specific strata ####

scup_fall <- scup_complete |>
  filter(SEASON == "FALL",
         STRATUM %in% strata_include_fall)

scup_spring <- scup_complete |>
  filter(SEASON == "SPRING",
         STRATUM %in% strata_include_spring)

na <- filter(scup_fall, is.na(AVGDEPTH)) # check for any na values
scup_fall <- scup_fall |> filter(!is.na(AVGDEPTH))
na <- filter(scup_spring, is.na(AVGDEPTH)) # check for any na values
scup_spring <- scup_spring |> filter(!is.na(AVGDEPTH))


scup_fall$ID <- seq.int(nrow(scup_fall))
scup_spring$ID <- seq.int(nrow(scup_spring))

```

```{r}
dist_fall <- ggplot(strata) + 
  geom_sf() +  
  geom_sf(data = scup_stratafilter_fall, fill = "lightcyan") +
  geom_sf(data = wind_areas, fill="darkblue", color="grey80") +
  geom_point(data=scup_fall, aes(x = DECDEG_BEGLON, y = DECDEG_BEGLAT), 
             color = "firebrick2", shape = 20, alpha=0.2) +   scale_size(range = c(.1,10)) +
  labs(title = "Fall distribution", x = "Long", y = "Lat")
 #geom_sf(data = subset(strata, STRATUM %in% c(3200)), fill = "red") 


dist_spring <- ggplot(strata) + 
  geom_sf() +  
  geom_sf(data = scup_stratafilter_spring, fill = "lightcyan") +
  geom_sf(data = wind_areas, fill="darkblue", color="grey80") +
  geom_point(data=scup_spring, aes(x = DECDEG_BEGLON, y = DECDEG_BEGLAT), 
             color = "firebrick2", shape = 20, alpha=0.2) +   scale_size(range = c(.1,10)) +
   labs(title = "Spring distribution", x = "Long", y = "Lat")
 #geom_sf(data = subset(strata, STRATUM %in% c(3200)), fill = "red") 
 

grid.arrange(dist_fall,dist_spring,ncol=2)
```
```{r}
dist_wt_fall <- ggplot(strata) + 
  geom_sf() +  
  geom_point(data=scup_fall, aes(x = DECDEG_BEGLON, y = DECDEG_BEGLAT, size=EXPCATCHWT), 
             color = "firebrick3", shape = 20, alpha=0.3) +   scale_size(range = c(.1,10)) +
  labs(title = "Fall distribution of catches (kg)", x = "Long", y = "Lat")
 #geom_sf(data = subset(strata, STRATUM %in% c(3200)), fill = "red") 


dist_wt_spring <- ggplot(strata) + 
  geom_sf() +  
  geom_point(data=scup_spring, aes(x = DECDEG_BEGLON, y = DECDEG_BEGLAT, size=EXPCATCHWT), 
             color = "firebrick3", shape = 20, alpha=0.5) +   scale_size(range = c(.1,10)) +
   labs(title = "Spring distribution of catches (kg)", x = "Long", y = "Lat")
 #geom_sf(data = subset(strata, STRATUM %in% c(3200)), fill = "red") 
 

grid.arrange(dist_wt_fall,dist_wt_spring,ncol=2)
```
```{r}
dist_num_fall <- ggplot(strata) + 
  geom_sf() +  
  geom_point(data=scup_fall, aes(x = DECDEG_BEGLON, y = DECDEG_BEGLAT, size=EXPCATCHNUM), 
             color = "coral", shape = 20, alpha=0.3) +   scale_size(range = c(.1,10)) +
  labs(title = "Fall distribution of catches (num)", x = "Long", y = "Lat")
 #geom_sf(data = subset(strata, STRATUM %in% c(3200)), fill = "red") 


dist_num_spring <- ggplot(strata) + 
  geom_sf() +  
  geom_point(data=scup_spring, aes(x = DECDEG_BEGLON, y = DECDEG_BEGLAT, size=EXPCATCHNUM), 
             color = "coral", shape = 20, alpha=0.5) +   scale_size(range = c(.1,10)) +
   labs(title = "Spring distribution of catches (num)", x = "Long", y = "Lat")
 #geom_sf(data = subset(strata, STRATUM %in% c(3200)), fill = "red") 
 

grid.arrange(dist_num_fall,dist_num_spring,ncol=2)
```

```{r}
plot_wt_fall <- scup_fall |>
  ggplot(aes(x=AVGDEPTH, y=EXPCATCHWT)) +
  geom_jitter(position=position_jitter(width=0.1, height=0.2), aes(), 
              show.legend = FALSE, alpha=0.9) +
  theme(strip.text.x = element_text(size=9, color="black", face="bold"), 
        axis.text.x = element_text(angle = 90)) +
  labs(title="Fall", subtitle = "(a)",
         x = "Temp",
         y = "Catch (kg)")

plot_wt_spring <- scup_spring |>
  ggplot(aes(x=AVGDEPTH, y=EXPCATCHWT)) +
  geom_jitter(position=position_jitter(width=0.1, height=0.2), aes(), 
              show.legend = FALSE, alpha=0.9) +
  theme(strip.text.x = element_text(size=9, color="black", face="bold"), 
        axis.text.x = element_text(angle = 90)) +
  labs(title="Spring", subtitle = "(b)",
         x = "Temp",
         y = "Catch (kg)")

grid.arrange(plot_wt_fall,plot_wt_spring, ncol=2)
```


Catch in number
```{r}

plot_num_fall <- scup_fall |>
  ggplot(aes(x=AVGDEPTH, y=EXPCATCHNUM)) +
  geom_jitter(position=position_jitter(width=0.1, height=0.2), aes(), 
              show.legend = FALSE, alpha=0.9) +
    geom_smooth(aes(x=AVGDEPTH, y=EXPCATCHNUM)) +
  theme(strip.text.x = element_text(size=9, color="black", face="bold"), 
        axis.text.x = element_text(angle = 90)) +
  labs(title="Fall", subtitle = "(a)",
         x = "Depth",
         y = "Catch (num)")

plot_num_spring <- scup_spring |>
  ggplot(aes(x=AVGDEPTH, y=EXPCATCHNUM)) +
  geom_jitter(position=position_jitter(width=0.1, height=0.2), aes(), 
              show.legend = FALSE, alpha=0.9) +
  geom_smooth(aes(x=AVGDEPTH, y=EXPCATCHNUM)) +
  theme(strip.text.x = element_text(size=9, color="black", face="bold"), 
        axis.text.x = element_text(angle = 90)) +
  labs(title="Spring", subtitle = "(b)",
         x = "Depth",
         y = "Catch (num)")

grid.arrange(plot_num_fall,plot_num_spring, ncol=2)
```
Catch in weight
```{r}
plot_wt_fall <- scup_fall |>
  ggplot(aes(x=AVGDEPTH, y=EXPCATCHWT)) +
  geom_jitter(position=position_jitter(width=0.1, height=0.2), aes(), 
              show.legend = FALSE, alpha=0.9) +
    geom_smooth(aes(x=AVGDEPTH, y=EXPCATCHWT)) +
  theme(strip.text.x = element_text(size=9, color="black", face="bold"), 
        axis.text.x = element_text(angle = 90)) +
  labs(title="Fall", subtitle = "(a)",
         x = "Depth",
         y = "Catch (weight)")

plot_wt_spring <- scup_spring |>
  ggplot(aes(x=AVGDEPTH, y=EXPCATCHWT)) +
  geom_jitter(position=position_jitter(width=0.1, height=0.2), aes(), 
              show.legend = FALSE, alpha=0.9) +
  geom_smooth(aes(x=AVGDEPTH, y=EXPCATCHWT)) +
  theme(strip.text.x = element_text(size=9, color="black", face="bold"), 
        axis.text.x = element_text(angle = 90)) +
  labs(title="Spring", subtitle = "(b)",
         x = "Depth",
         y = "Catch (weight)")

grid.arrange(plot_wt_fall,plot_wt_spring, ncol=2)
  

```
Remove outliers

```{r}

scup_fall <- scup_fall |>
  filter(AVGDEPTH <= 150,
         ID != 314) #depth 104m and catch num 19491

```

```{r}
fall_dist_hist <- ggplot(scup_fall, aes(EXPCATCHNUM)) + geom_histogram(bins = 100)  + xlim(NA,100) + ggtitle("Fall")

spr_dist_hist <- ggplot(scup_spring, aes(EXPCATCHNUM)) + geom_histogram(bins = 100)  + xlim(NA,100) + ggtitle("Spring")

grid.arrange(fall_dist_hist,spr_dist_hist, ncol=2)

```

Distribution of all the variables - FALL
```{r}
mean.data.yr.f <- scup_fall |> 
        group_by(YEAR) |>
        summarise(mean.catch_n = round(mean(EXPCATCHNUM), digits = 2)) 

Year.f <- mean.data.yr.f |>
  ggplot(aes(x=YEAR, y=mean.catch_n)) +
  geom_point(alpha = 0.9, show.legend = FALSE) +
  geom_smooth(method = "gam", formula = y~s(x, k=9))


lat.f <- scup_fall |>
  ggplot(aes(x=DECDEG_BEGLAT, y=EXPCATCHNUM)) +
  geom_point(alpha = 0.9, show.legend = FALSE) +
  geom_smooth(method = "gam", formula = y~s(x, k=9))

lon.f <- scup_fall |>
  ggplot(aes(x=DECDEG_BEGLON, y=EXPCATCHNUM)) +
  geom_point(alpha = 0.9, show.legend = FALSE) +
  geom_smooth(method = "gam", formula = y~s(x, k=9))



Depth.f <- scup_fall |>
  ggplot(aes(x=AVGDEPTH, y=EXPCATCHNUM)) +
  geom_point(alpha = 0.9, show.legend = FALSE) +
  geom_smooth(method = "gam", formula = y~s(x, k=9))


library(patchwork)
(Year.f + Depth.f + lat.f + lon.f) + plot_layout(ncol = 2, widths = c(1,1), guides = "collect")


```

Distribution of all the variables - SPRING
```{r}
mean.data.yr.s <- scup_spring |> 
        group_by(YEAR) |>
        summarise(mean.catch_n = round(mean(EXPCATCHNUM), digits = 2)) 

Year.s <- mean.data.yr.s |>
  ggplot(aes(x=YEAR, y=mean.catch_n)) +
  geom_point(alpha = 0.9, show.legend = FALSE) +
  geom_smooth(method = "gam", formula = y~s(x, k=9))


lat.s <- scup_spring |>
  ggplot(aes(x=DECDEG_BEGLAT, y=EXPCATCHNUM)) +
  geom_point(alpha = 0.9, show.legend = FALSE) +
  geom_smooth(method = "gam", formula = y~s(x, k=9))


lon.s <- scup_spring |>
  ggplot(aes(x=DECDEG_BEGLON, y=EXPCATCHNUM)) +
  geom_point(alpha = 0.9, show.legend = FALSE) +
  geom_smooth(method = "gam", formula = y~s(x, k=9))


Depth.s <- scup_spring |>
  ggplot(aes(x=AVGDEPTH, y=EXPCATCHNUM)) +
  geom_point(alpha = 0.9, show.legend = FALSE) +
  geom_smooth(method = "gam", formula = y~s(x, k=9))


library(patchwork)
(Year.s + Depth.s + lat.s + lon.s) + plot_layout(ncol = 2, widths = c(1,1), guides = "collect")

```


```{r}
data.yr.f <- scup_fall |> 
        group_by(YEAR) |>
        summarise(mean.catch_n = round(mean(EXPCATCHNUM), digits = 2),
                  var.catch_n = round(var(EXPCATCHNUM), digits = 2)) 



```

```{r}

(strata.overlap <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = wind_areas1, fill="navyblue", color="grey80", alpha=0.5) +
    geom_sf(data = subset(strata, STRATUM %in% c(3200)), fill = "firebrick2", alpha=0.4) +
    coord_sf() + 
    labs(title = "", x = "Longitude", y = "Latitude", fill = "") +
    theme_bw() + theme(plot.title = element_text(size=10),plot.subtitle = element_text(size=7)) +
    theme(legend.position = "bottom", panel.grid = element_blank()))
```

```{r}

(so.zoom.in <- ggplot() + 
    geom_sf(data = strata, fill = "white", color = "grey80") + 
    geom_sf(data = coastline, fill = "grey60", color = "black") + 
    geom_sf(data = wind_areas2, fill="navyblue", color="grey80", alpha=0.5) +
    geom_sf(data = subset(strata, STRATUM %in% c(3200)), fill = "firebrick2", alpha=0.4) +
    coord_sf(xlim = c(-73,-75), ylim=c(38,40), expand = FALSE) + 
    labs(title = "", x = "Longitude", y = "Latitude", fill = "") +
    theme_bw() + theme(plot.title = element_text(size=10),plot.subtitle = element_text(size=7)) +
    theme(legend.position = "bottom", panel.grid = element_blank()))
```


```{r}
strata |> filter(STRATUM == 3200)

```